name: contexts demo
on: [push]

jobs:
  #Job name
  github-context:
   runs-on: ubuntu-latest
   steps:
   - name: print info
     run: echo "${{toJson(github)}}"
          echo "branch name: ${{github.ref_name}}"

   - name: access env variables
     run: 
       echo "project: $project"
       echo "component: $component"
       echo "Environment: $environment"
    
   -  name: print secrets
      run:
        echo "DB user: ${{secrets.DB_USER}}" 
        echo "DB password: ${{secrets.DB_PASSWORD}}"