name: contexts demo

on: [push]

env:
  project: my-project
  component: frontend
  environment: dev

jobs:
  context-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Access env variables
        run: |
          echo "Project: $project"
          echo "Component: $component"
          echo "Environment: $environment"

      - name: Print secrets
        run: |
          echo "DB user: ${{ secrets.DB_USER }}"
          echo "DB password: ${{ secrets.DB_PASSWORD }}"